version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.Resources.Extensions
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: Analogy.LogViewer.Interfaces
    versions:
    - 2.10.0
